name: Deploy to Github Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Build:
    if: github.ref == 'refs/heads/main' && github.actor == 'Lyandiff'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Echo
        run: |
          echo "${{ github.event.repository.name }}" >> index.txt
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            .
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
